name: Run Auto Generate JSON with C# File

on:
  push:
    branches:
      - main
      - master
      - Skua
      - dev
      - 'feature/*'

jobs:
  run-csharp-file:
    runs-on: ubuntu-latest

    steps:
    # === Step: Checkout Code ===
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    # === Step: Cache NuGet Packages ===
    - name: Cache NuGet packages
      uses: actions/cache@v4.2.0
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/*.cs') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    # === Step: Setup .NET ===
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4.2.0
      with:
        dotnet-version: '8.0.x'

    # === Step: Build the Project ===
    - name: Build the project
      run: dotnet build --configuration Release SkuaScriptsGenerator/SkuaScriptsGenerator.csproj

    # === Step: Run C# File ===
    - name: Run C# file
      run: dotnet run --project SkuaScriptsGenerator/SkuaScriptsGenerator.csproj 2>/dev/null > scripts.json

    # === Step: Upload Artifact (only if changes are detected) ===
    - name: Upload artifact
      uses: actions/upload-artifact@v4.6.0
      with:
        name: scripts-${{ github.run_id }}.json
        path: scripts.json
        retention-days: 60

    # === Step: Commit and Push Changes (only if changes are detected) ===
    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v5.1.0
      with:
        commit_message: 'Automatic commit by GitHub Actions'
        file_pattern: 'scripts.json'
        push_options: '--force'
        branch: '${{ github.ref_name }}'
